
const util = require('./util');

function getRandomName() {

    const names = [
        "Jemma Sampson",
        "Kairo Howell",
        "Rahima Christian",
        "Hina Serrano",
        "Britany Weber",
        "Nicholas Connelly",
        "Elisabeth Guest",
        "Parris Hayward",
        "Ellisha Daniel",
        "Harper-Rose Bains",
        "Jeanette George",
        "Mazie Frame",
        "Ciara Grey",
        "Charles Kouma",
        "Emmeline Higgs",
        "Ava-Rose Goddard",
        "Lilliana Miles",
        "Ainsley Blundell",
        "Rebekah Tran",
        "Madiha Caldwell",
        "Nyle Almond",
        "Poppie Leonard",
        "Ishaq Franco",
        "Samantha Sharma",
        "Shayaan Wharton",
        "Zahra Rogers",
        "Maggie Tanner",
        "Yasemin Berry",
        "Hamish Mccann",
        "Momina Terrell",
        "Spencer Mcnamara",
        "Aaran Millington",
        "Menna Harris",
        "Kuba Harvey",
        "Johnathan Hough",
        "Mara Shea",
        "Macy Lynn",
        "Stanislaw Miranda",
        "Indiana Sierra",
        "Evie-Mai Timms",
        "Jasper Dodson",
        "Nyla Hodson",
        "Colin Downs",
        "Carmen Mayo",
        "Jodi Dunne",
        "Ella-Louise Churchill",
        "Jose Feeney",
        "Ammar Hills",
        "Neriah Simons",
        "Hadiqa Vu",
        "Luc Cordova",
        "Arbaaz Preston",
        "Karolina Mcbride",
        "Danny Watt",
        "Sorcha Pratt",
        "Alistair Contreras",
        "Arthur Baird",
        "Dwayne Mays",
        "Khadeeja Burrows",
        "Adela Maddox",
        "Riyad Singleton",
        "Arwa Barrera",
        "Leen Schwartz",
        "Dua Barker",
        "Chandni Cash",
        "Patience Davis",
        "Iona Gibbons",
        "Penny Estrada",
        "Nimrah Velez",
        "Mikail Greenwood",
        "Ishmael Jacobs",
        "Nikodem Marks",
        "Caoimhe Mckinney",
        "Hadassah Carr",
        "Kaylan Lim",
        "Star Calhoun",
        "Osama Hendricks",
        "Henna Carson",
        "Maksim Sherman",
        "Reece Farrell",
        "Wendy Martin",
        "Cassie Ratcliffe",
        "Arooj Betts",
        "Nikhil Sparrow",
        "Audrey Parker",
        "Ava Head",
        "Carolyn Whittington",
        "Enrico Irving",
        "Rebeca Whitehead",
        "Khalil Wicks",
        "Sydney Mustafa",
        "Shaunie Barton",
        "Gaia Garner",
        "Elaina Frost",
        "Blane Magana",
        "Catherine Avalos",
        "Abubakar Aldred",
        "Aliesha Curtis",
        "Lachlan Rooney",
        "Lexi Cunningham"
    ];

    return names[util.getRandomArbitrary(0, names.length - 1)];
}

exports.getRandomName = getRandomName;